empty={}
lang=input("Your fav language : ")
name=input("ENTER your name 1: ")
empty.update({name:lang})
lang=input("Your fav language : ")
name=input("ENTER your name 2: ")
empty.update({name:lang})
lang=input("Your fav language : ")
name=input("ENTER your name 3: ")
empty.update({name:lang})
lang=input("Your fav language : ")
name=input("ENTER your name 4: ")
empty.update({name:lang})
print(empty)
print(empty.keys(),"likes",empty.values())
