number=int(input("enter number : "))
empty=set()
empty.add(number)
number=int(input("enter number : "))
empty.add(number)
number=int(input("enter number : "))
empty.add(number)
number=int(input("enter number : "))
empty.add(number)
number=int(input("enter number : "))
empty.add(number)
number=int(input("enter number : "))
empty.add(number)
number=int(input("enter number : "))
empty.add(number)
number=int(input("enter number : "))
empty.add(number)
print(empty)