fruits=[]
a=input("ENTER NAME OF A FRUIT 1 : ")
fruits.append(a)
a=input("ENTER NAME OF A FRUIT 2 : ")
fruits.append(a)
a=input("ENTER NAME OF A FRUIT 3 : ")
fruits.append(a)
a=input("ENTER NAME OF A FRUIT 4 : ")
fruits.append(a)
a=input("ENTER NAME OF A FRUIT 5 : ")
fruits.append(a)
a=input("ENTER NAME OF A FRUIT 6 : ")
fruits.append(a)
print(fruits)